vars:
  - SIM_RES_CONFIG_DIR: "../../results/init_config"
  - SIM_RES_ANNL_DIR: "../../results/annealing"
  - SIM_RES_FREE_EQ_DIR: "../../results/free_equilibrium"
  - SIM_RES_FREE_EN_DIR: "../../results/free_energy"

stages:
  free_energy:
    cmd: 
      - mkdir -p ${SIM_RES_FREE_EN_DIR}
      - echo "gmx grompp -f sim_md.mdp -c npt_out.gro -p topol_gas.top -o md_out.tpr" > ${SIM_RES_FREE_EN_DIR}/md_out.tpr
      - echo "gmx mdrun -deffnm md_out -nt 28"
      - echo "gmx energy -f md_out.edr -o energy.xvg" > ${SIM_RES_FREE_EN_DIR}/energy.xvg
    # params:
    #   - nvt_1_ns
    deps:
     - ${SIM_RES_CONFIG_DIR}/init_conf.gro
     - ${SIM_RES_ANNL_DIR}/cooling_out.tpr
    outs:
      - ${SIM_RES_FREE_EN_DIR}/md_out.tpr
      - ${SIM_RES_FREE_EN_DIR}/energy.xvg